package com.example.tvclient.presentation

const val TV_DETAIL_REQUEST_KEY = "TV_DETAIL_REQUEST"
const val TV_DETAIL_RESULT_KEY = "TV_DETAIL_RESULT"
const val SIMPLE_DIALOG_REQUEST_KEY = "SIMPLE_DIALOG_REQUEST"
const val SIMPLE_DIALOG_RESULT_KEY = "SIMPLE_DIALOG_RESULT"
